# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-04 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='tag_order',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
