# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-04 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20180104_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='tag_order',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='graph',
            name='tag',
            field=models.ManyToManyField(blank=True, to='storage.Tag'),
        ),
        migrations.AlterField(
            model_name='graph',
            name='url',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='tag',
            name='image_order',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
