# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-05 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_auto_20180104_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='display_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
