# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-05 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_tag_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='version',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='app',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='app',
            name='tag_order',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tag',
            name='display_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
