# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-05 08:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_graph_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 5, 8, 49, 13, 279064, tzinfo=utc), verbose_name='upload date'),
        ),
    ]
