# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-12 06:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_auto_20180105_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.CharField(blank=True, default='', max_length=400)),
            ],
        ),
        migrations.AlterField(
            model_name='graph',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 12, 6, 50, 56, 858087, tzinfo=utc), verbose_name='upload date'),
        ),
        migrations.AlterUniqueTogether(
            name='app',
            unique_together=set([('name',)]),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set([('name',)]),
        ),
        migrations.AddField(
            model_name='package',
            name='graph',
            field=models.ManyToManyField(blank=True, to='storage.Graph'),
        ),
    ]
