# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-12 08:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0012_auto_20180112_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 12, 8, 21, 8, 493415, tzinfo=utc), verbose_name='upload date'),
        ),
    ]
