# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-29 08:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0017_auto_20180129_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 29, 8, 29, 16, 881828, tzinfo=utc), verbose_name='upload date'),
        ),
        # migrations.AlterField(
        #     model_name='tag',
        #     name='cover',
        #     field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='cover', to='storage.Graph'),
        # ),
    ]
