# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-30 00:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0020_auto_20180130_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 30, 0, 42, 54, 753314, tzinfo=utc), verbose_name='upload date'),
        ),
    ]
