# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-05 01:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0022_auto_20180130_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='force_update_version',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='graph',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 5, 1, 47, 0, 3293, tzinfo=utc), verbose_name='upload date'),
        ),
    ]
