# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-26 05:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0025_auto_20180205_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='app',
            field=models.ManyToManyField(to='storage.App'),
        ),
        migrations.AlterField(
            model_name='graph',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 26, 5, 56, 38, 290231, tzinfo=utc), verbose_name='upload date'),
        ),
    ]
