# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-26 05:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0026_auto_20180226_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 26, 5, 58, 1, 506891, tzinfo=utc), verbose_name='upload date'),
        ),
        migrations.AlterField(
            model_name='package',
            name='app',
            field=models.ManyToManyField(blank=True, to='storage.App'),
        ),
    ]
