# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-02 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0028_auto_20180302_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='upload date'),
        ),
    ]
