# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-16 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0031_feature_click'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='click',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='storage.Tag'),
        ),
    ]
