# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-04 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0032_auto_20180316_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='starting',
            field=models.BooleanField(default=False),
        ),
    ]
