# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-10 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0033_graph_starting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='original_url',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='graph',
            name='url',
            field=models.CharField(default='', max_length=400),
        ),
    ]
