# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-28 10:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0034_auto_20180710_1337'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Category',
        ),
    ]
