# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-08-28 10:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0035_auto_20180828_1003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='app',
            old_name='tag_order',
            new_name='category_order',
        ),
        migrations.RenameField(
            model_name='graph',
            old_name='tag',
            new_name='category',
        ),
    ]
