# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-11-20 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0036_auto_20180828_1011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graph',
            options={'ordering': ['-date']},
        ),
    ]
